# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
tank1 = Tank.create(name: 'ÁGUAS-VIVAS', order: 1)
Tank.create(name: 'PRAIAS ARENOSAS: PEIXES QUE SE ENTERRAM', order: 2)
tank3 = Tank.create(name: 'PRAIAS ARENOSAS: INVASÃO BIOLÓGICA', order: 3)
Tank.create(name: 'PRAIAS ARENOSAS: PEIXES DA AREIA', order: 4)
Tank.create(name: 'ANIMAIS MARINHOS PERIGOSOS', order: 5)
Tank.create(name: 'COSTÃO ROCHOSO – INVERTEBRADOS', order: 6)
Tank.create(name: 'COSTÃO ROCHOSO – PEIXES', order: 7)
Tank.create(name: 'COSTÃO ROCHOSO - DONZELAS', order: 8)
Tank.create(name: 'COSTÃO ROCHOSO - INFRALITORAL', order: 9)
Tank.create(name: 'COSTÃO ROCHOSO – ESTRELAS', order: 10)
Tank.create(name: 'CARDUMES', order: 11)
tank12 = Tank.create(name: 'TUBARÕES E RAIAS BEBÊS', order: 12)
tank13 = Tank.create(name: 'TUBARÕES DE PEQUENO PORTE', order: 13)
tank14 = Tank.create(name: 'ESTRATÉGIA BIOLÓGICA: FORMAS DO CORPO', order: 14)
Tank.create(name: 'ESTRATÉGIA BIOLÓGICA: PEIXES QUE PESCAM', order: 15)
Tank.create(name: 'ESTRATÉGIA BIOLÓGICA: ASSOCIAÇÃO', order: 16)
Tank.create(name: 'ESTRATÉGIA BIOLÓGICA: POLVO', order: 17)
Tank.create(name: 'MAR GELADO', order: 18)
Tank.create(name: 'PEIXES DA ILHA DA TRINDADE', order: 19)
Tank.create(name: 'PEIXES DO CARIBE', order: 20)
tank21 = Tank.create(name: 'CORAIS DO BRASIL', order: 21)
Tank.create(name: 'PEIXES DO INDO-PACÍFICO', order: 22)
Tank.create(name: 'CORAIS INDO-PACÍFICO', order: 23)
tank24 = Tank.create(name: 'OCEÂNICO', order: 24)
Tank.create(name: 'BIJUPIRÁS', order: 25)
Tank.create(name: 'TANQUE DE TOQUE', order: 26)

tank1.researches.create(title: 'Desenvolvimento de protetor contra queimadura de cnidários presentes nas costas marítimas.', description: 'Os tentáculos das águas-vivas e caravelas (cnidários) possuem células urticantes (nematocistos) contendo toxinas com efeito paralisante em presas menores, mas que na pele humana provocam vermelhidão e dor. O estudo aborda o desenvolvimento de um protetor para evitar que essas células urticantes consigam penetrar na pele e inocular a peçonha, evitando, consequentemente, que as pessoas sejam queimadas pelo animal.', author: 'Bruna Marschner (TCC)', image: 'aguaviva.png')
tank3.researches.create(title: 'Experimentos anti-incrustação e de intolerância a diferentes temperaturas da água em cracas nativas e invasoras.', description: 'O estudo é pioneiro no desenvolvimento de um protocolo de cultivo de espécies nativas e invasoras de cracas do gênero Megabalanus, comum em navios e plataformas de petróleo. Tem como propósito testar agentes anti-incrustantes nas larvas e a sobrevivência de adultos submetidos a diferentes temperaturas da água. Esses resultados serão de interesse para diferentes indústrias, e permitirão melhor orientação quanto o controle, manutenção e erradicação de espécies invasoras.', author: 'Mauricio Peixoto Scapolatempore, MSc. (Projeto de Doutorado)')
tank12.researches.create(title: 'Reprodução do tubarão-bambu Chiloscyllium punctatum.', description: 'Trabalho que visa gerar um protocolo sobre a reprodução de tubarões-bambu (Chiloscyllium punctatum) em cativeiro, acompanhando os intervalos entre as desovas, o período de crescimento do embrião e, posteriormente, o crescimento dos filhotes no AquaRio', author: 'Fábio Sendin, BSc. (AquaRio)')
tank13.researches.create(title: 'Reprodução do tubarão-bambu Chiloscyllium punctatum.', description: 'Trabalho que visa gerar um protocolo sobre a reprodução de tubarões-bambu (Chiloscyllium punctatum) em cativeiro, acompanhando os intervalos entre as desovas, o período de crescimento do embrião e, posteriormente, o crescimento dos filhotes no AquaRio', author: 'Fábio Sendin, BSc. (AquaRio)')
tank14.researches.create(title: 'Reprodução do Hippocampus reidi em cativeiro.', description: 'Pesquisa que visa adquiri conhecimentos sobre a melhor forma de cultivo e desenvolvimento do cavalo marinho (Hippocampus reidi). Os resultados poderão subsidiar novas estratégias para preservação dessa espécie, colaborando assim com o restabelecimento da fauna nativa, em locais prévios ou futuros em que esta espécie esteja extinta.', author: 'Miria Baracho e Ingrid Alves (Monografia)', image: 'formas.png')
tank21.researches.create(title: 'Reprodução do peixe Elacatinus figaro..', description: 'Estudo que tem como objetivo melhorar a reprodução em cativeiro do peixe Neon goby (Elacatinus fígaro), através do acompanhamento do desenvolvimento de suas larvas. Essa espécie é endêmica do nosso litoral e está ameaçada de extinção.', author: 'Fabricio Nogueira e Rafael Franco Valle (AquaRio)')
tank21.researches.create(title: 'Estudo inovador que visa a proteger e recuperar recifes de corais do mundo inteiro ameaçados pelo branqueamento e outras doenças. A abordagem inovadora dessa pesquisa em andamento, que tem se mostrado extremamente sustentável e viável e que visa a proteger e recuperar recifes de corais do mundo inteiro ameaçados pelo branqueamento e outras doenças, estabelece a manipulação benéfica dos microbiomas naturais marinhos, que já estão lá e são nativos desses ecossistemas, para proteger esses ambientes coralinos.', author: 'Dr. Gustavo Duarte (Projeto de Pós-Doutorado), Phillipe Rosado Magalhães (Tese de Doutorado), Erika Peçanha Santoro (Tese de Doutorado), Helena Dias Müller Villela (Tese de Doutorado) e Camila Messias (Monografia).')
tank24.researches.create(title: 'Avaliação hematológica dos animais do AquaRio.', description: 'Pouco se sabe sobre a caracterização hematológica de muitos animais marinhos, principalmente peixes e elasmobrânquios. A pesquisa tem como objetivo fazer avaliação hematológica dos animais mantidos em cativeiro pelo AquaRio, de modo a ter o controle sanitário dos animais, pesquisar hemoparasitoses, diagnosticar possíveis doenças e padronizar os valores hematológicos e bioquímicos', author: 'Lara Meyer (Tese de mestrado)', image: 'oceanico.png')
tank24.researches.create(title: 'Caracterização do uso do espaço por peixes no tanque oceânico.', description: 'Nesse estudo iremos identificar a forma de uso do espaço, em uma escala tridimensional, dos organismos presentes no tanque oceânico do AquaRio, que será setorizado, tanto na profundidade, quanto na largura e um conjunto de câmeras fotográficas, equipadas com sensores de movimento. Estas câmeras serão instaladas de forma a registrar a movimentação das distintas espécies (e quando possível de cada indivíduo, como dos peixes de maior porte) por um período ininterrupto. Os dados obtidos (fotografias) vão ser trabalhados e analisados de forma a identificar se existem preferencias especificas e ou individuais.', author: 'Prof. Dr. Marcelo Vianna (Laboratório de Biologia e Tecnologia Pesqueira – UFRJ)', image: 'oceanico.png')
tank24.researches.create(title: 'Diversidade microbiana em raias costeiras', description: 'Importante pesquisa para estudar o “ecossistema hospedeiro animal”, também chamado microbioma, com o objetivo de fornecer informações importantes para lidar com infecções secundárias no homem e para favorecer a manutenção da saúde dessas raias.', author: 'Mestranda Fernanda Golçalves e Silva (Dissertação de Doutorado)', image: 'oceanico.png')
tank24.researches.create(title: 'Morfologia do embrião de raia-elétrica Narcine brasilienses.', description: 'Trabalho que visa descrever a morfologia do embrião da raia-elétrica Narcine brasilienses, identificando as etapas do desenvolvimento ao longo da gestação, buscando dimorfismo sexual entre machos e fêmeas e comparando os diferentes estágios de crescimento desde o embrião, neonato até o indivíduo adulto.', author: 'Ana Carolina Pereira dos Santos (Monografia de Iniciação Científica)', image: 'oceanico.png')
tank24.researches.create(title: 'Transferência de mircobiota materna.', description: 'Pesquisa inédita com raias e tubarões com o intuito de identificar se há nos elasmobrânquios a transferência da microbiota materna, ou seja, as bactérias que habitam o ser vivo, para os filhotes, assim como ocorre nos mamíferos, ou se a microbiota é adquirida após o nascimento.', author: 'Prof. Dr. Marcelo Vianna (Laboratório de Biologia e Tecnologia Pesqueira – UFRJ), Profa Dra Raquel S. Peixoto e Prof. Dr. Alexandre Rosado (Laboratório de Ecologia Microbiana Molecular – UFRJ).', image: 'oceanico.png')
